import SignupCode from "./signupCode.model";
import { ISignupCodeDocument } from "./signupCode.interface";
import Logging from "../../library/logging";

const generateRandomCode = (): string => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let result = '';
  for (let i = 0; i < 6; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

export const generateSignupCode = async (
  adminId: string,
  maxUsages: number,
  expiresAt?: Date
): Promise<ISignupCodeDocument> => {
  try {
    let code: string;
    let existingCode: ISignupCodeDocument | null;

    do {
      code = generateRandomCode();
      existingCode = await SignupCode.findOne({ code });
    } while (existingCode);

    const signupCode = await SignupCode.create({
      code,
      maxUsages,
      currentUsages: 0,
      isActive: true,
      createdBy: adminId,
      expiresAt,
    });

    Logging.log(`Signup code ${code} generated by admin ${adminId}`);
    return signupCode;
  } catch (error: any) {
    Logging.error(`Error generating signup code: ${error.message}`);
    throw new Error("Failed to generate signup code");
  }
};

export const validateAndUseSignupCode = async (code: string): Promise<boolean> => {
  try {
    const signupCode = await SignupCode.findActiveCode(code);
    
    if (!signupCode) {
      Logging.log(`Invalid or expired signup code attempted: ${code}`);
      return false;
    }

    if (signupCode.currentUsages >= signupCode.maxUsages) {
      Logging.log(`Signup code ${code} has reached maximum usage limit`);
      return false;
    }

    const updatedCode = await SignupCode.incrementUsage(code);
    
    if (!updatedCode) {
      Logging.log(`Failed to increment usage for signup code: ${code}`);
      return false;
    }

    Logging.log(`Signup code ${code} used successfully. Usage: ${updatedCode.currentUsages}/${updatedCode.maxUsages}`);
    return true;
  } catch (error: any) {
    Logging.error(`Error validating signup code: ${error.message}`);
    return false;
  }
};

export const getSignupCodesByAdmin = async (adminId: string): Promise<ISignupCodeDocument[]> => {
  try {
    const codes = await SignupCode.find({ createdBy: adminId })
      .sort({ createdAt: -1 })
      .exec();
    return codes;
  } catch (error: any) {
    Logging.error(`Error fetching signup codes for admin ${adminId}: ${error.message}`);
    throw new Error("Failed to fetch signup codes");
  }
};

export const getAllActiveSignupCodes = async (): Promise<ISignupCodeDocument[]> => {
  try {
    const codes = await SignupCode.find({ 
      isActive: true,
      $or: [
        { expiresAt: { $exists: false } },
        { expiresAt: null },
        { expiresAt: { $gt: new Date() } }
      ]
    })
      .populate('createdBy', 'auth.username auth.email')
      .sort({ createdAt: -1 })
      .exec();
    return codes;
  } catch (error: any) {
    Logging.error(`Error fetching all active signup codes: ${error.message}`);
    throw new Error("Failed to fetch signup codes");
  }
};

export const updateSignupCode = async (
  codeId: string,
  adminId: string,
  updates: Partial<ISignupCodeDocument>
): Promise<ISignupCodeDocument | null> => {
  try {
    const signupCode = await SignupCode.findOneAndUpdate(
      { _id: codeId, createdBy: adminId },
      updates,
      { new: true }
    );

    if (!signupCode) {
      Logging.log(`Signup code ${codeId} not found or admin ${adminId} not authorized`);
      return null;
    }

    Logging.log(`Signup code ${signupCode.code} updated by admin ${adminId}`);
    return signupCode;
  } catch (error: any) {
    Logging.error(`Error updating signup code: ${error.message}`);
    throw new Error("Failed to update signup code");
  }
};

export const deactivateSignupCode = async (
  codeId: string,
  adminId: string
): Promise<boolean> => {
  try {
    const result = await SignupCode.findOneAndUpdate(
      { _id: codeId, createdBy: adminId },
      { isActive: false },
      { new: true }
    );

    if (!result) {
      Logging.log(`Signup code ${codeId} not found or admin ${adminId} not authorized`);
      return false;
    }

    Logging.log(`Signup code ${result.code} deactivated by admin ${adminId}`);
    return true;
  } catch (error: any) {
    Logging.error(`Error deactivating signup code: ${error.message}`);
    return false;
  }
};




